repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.0
    hooks:
      - id: mypy
        pass_filenames: false
        args:
          - "--config-file=mypy.ini"
          - "app"
        additional_dependencies:
          - pydantic-settings>=2.0
          - pydantic>=2.0
          - fastapi
